# Generated by Django 4.1.1 on 2022-09-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_filedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filedata',
        ),
    ]
