# Generated by Django 4.1.1 on 2022-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_userposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='caption',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
